name: Nicholas Van Exan
markdown: kramdown

collections:
  my_categories:
    output: true
    permalink: /blog/category/:name/
  my_tags:
    output: true
    permalink: /blog/tag/:name/

gems:
  - jekyll-paginate

permalink: /blog/post/:title/
paginate: 5
paginate_path: '/blog/page/:num/'
