name: Nicholas Van Exan
markdown: kramdown
description: Privacy lawyer and software development consultant working at the intersection of law and data in Toronto.

collections:
  my_categories:
    output: true
    permalink: /blog/category/:name/
  my_tags:
    output: true
    permalink: /blog/tag/:name/

gems:
  - jekyll-paginate

permalink: /blog/post/:year/:month/:day/:title/
paginate: 5
paginate_path: '/blog/page/:num/'
